### ISSUE TITLE
Not working with gradle output?

### ISSUE THREAD

**Issue by dkim19375** [ajalt/mordant#104]
Regular ANSI color codes work fine, but not ones from Mordant:
```kt
import com.github.ajalt.mordant.rendering.TextColors.red
import com.github.ajalt.mordant.terminal.Terminal

fun main() {
    val t = Terminal()
    t.println(red("This isn't red!"))
    println("\u001B[31mThis is red\u001B[0m")
}
```

`gradle run` output: 
![image](https://github.com/ajalt/mordant/assets/65050767/092f649a-b23c-457c-933c-d848bd0a337a)

However, `java -jar BuiltJar.jar` works fine

I also have tried to put `org.gradle.console=rich` in my `gradle.properties`, but it doesn't seem to do anything

**Comment by ajalt** [comment]
By default, Mordant disables colors and animations when stdout is redirected so that it doesn't write ANSI codes to files. Since Gradle captures the output, it causes colors to be disabled.

If you want, you can force colors with `Terminal(AnsiLevel.TRUECOLOR, interactive=true)`.

What I do is avoid the `run` task, and instead use `installDist` then run the binary directly. [Here's an example of that][1]

[1]: https://github.com/ajalt/clikt/blob/master/runsample
