### ISSUE TITLE
Variable naming: "animation" vs. "progress"

### ISSUE THREAD

**Issue by sschuberth** [ajalt/mordant#211]
It's just a small thing, but there currently seems to be some inconsistency on how the variables in example code / docs are named: Somtimes it's

https://github.com/ajalt/mordant/blob/f4c9daa00f54f7363af10a84e229aa5730ab3f96/docs/progress.md?plain=1#L26

and sometimes

https://github.com/ajalt/mordant/blob/f4c9daa00f54f7363af10a84e229aa5730ab3f96/samples/drawing/src/commonMain/kotlin/com/github/ajalt/mordant/samples/main.kt#L45

If you have a clear preference of "animation" vs. "progress" I'd be happy to align that.

**Comment by ajalt** [comment]
Well, those are two different types: `animation` is a `CoroutineAnimator`, while `progress` is a `CoroutineProgressAnimator`. I definitely wouldn't change them both to `progress`, since the drawing example is unrelated to progress. So if I had to pick one, I guess I'd go with `animation`, but I'm not sure they need to have the same name.

**Comment by sschuberth** [comment]
Yeah, my thinking was as both class names end with "...Animator", the variable names should all be "animation". But I see where you're coming from. Thanks for the explanation, let's just close this.
