### ISSUE TITLE
Some characters break table layout by some width offset

### ISSUE THREAD

**Issue by Zordid** [ajalt/mordant#237]
In my input data, some people use special characters like "ツ" in their user names.

When those are embedded into table cells created by the `TableBuilder`, the vertical lines stop lining up precisely... 

Could this be fixed? Or what can I do? I mean, yes, I can filter out anything that is not a "normal" ASCII char, but then the username displayed would be wrong...

Thanks!

**Comment by ajalt** [comment]
![image](https://github.com/user-attachments/assets/f5a152cb-5d8c-4622-b037-af129bc13598)
That character is being aligned correctly from mordant's perspective. If it's not lining up, that's due to the font you're using on your terminal. If the font doesn't use a fixed width for unicode characters, the table won't line up, and there's nothing that mordant can do about that.

**Comment by Zordid** [comment]
I am seeing the problem in IntelliJ's run console window. I tried almost ALL monospaced fonts available on my Mac, of course starting with Jetbrains Mono, Firacode, Courier New, etc. 
None of them make the alignment work.

Any chance there are other things that play a role in this situation?

**Comment by ajalt** [comment]
If you write the table by hand, just using a string literal with your own spacing instead of mordant, can you get it to line up? If so, then it might be a mordant issue. But AFAIK there are no unicode fonts that line up 100% of glyphs to the cell width, so it's never going to be perfect.
