### ISSUE TITLE
Support for Kotlin 1.4?

### ISSUE THREAD

**Issue by GGorAA** [ajalt/mordant#5]
As in title

**Comment by ajalt** [comment]
I'll definitely update Mordant's dependencies for its next release. 

Are you experiencing bugs when using the current version of Mordant with Kotlin 1.4? It's worked fine for me.

**Comment by JakeWharton** [comment]
Works fine on 1.4 here, too.

**Comment by GGorAA** [comment]
No bugs for me, but it will be better when library supports latest Kotlin release)

**Comment by JakeWharton** [comment]
Kotlin is forward compatible such that you never have to update to support a new release. In fact, bumping for no purpose should be discouraged since you arbitrarily force your users onto a newer version where they may not need it. This is especially true for multiplatform projects which are _not_ forward compatible and require work to migrate.

https://kotlinlang.org/docs/reference/evolution/components-stability.html

**Comment by GGorAA** [comment]
Now I understand. Thx for explanation)
