### ISSUE TITLE
Is there a way to display several progress bars? 

### ISSUE THREAD

**Issue by yoelp2k** [ajalt/mordant#62]
Hi!

I really enjoy your code, you are super talented and I learned many cool Kotlin tricks reading your code :)

My issue is:
I want to present several progress bars. Simple use case will be downloading two (or more) files simultaneously - trying to display a progress-bar per file 

I tried several approaches utilizing progressAnimation, one terminal with multiple progress bars, and several terminals with progressAnimation each. Digging a little into the code I realized that this is not the way that I should use your code 
Sadly my attempts failed miserably :(

My workaround is not using the progress bars at all and using styled text instead - but I feel like there is possibly a better solution  

Can you please hint to me about what should I do?

Thanks a bunch!! 

(p.s. I don't mind having both progress bars at the same line but I would prefer them one per line)

**Comment by ajalt** [comment]
Sure, just use one terminal and make two progress animations:
```kotlin
val terminal = Terminal()
val progress = terminal.progressAnimation { progressBar() }
val progress2 = terminal.progressAnimation { progressBar() }

progress.start()
progress2.start()
```

Or, if you did want two bars on the same line, put them both in the same animation:
```kotlin
val terminal = Terminal()
val progress = terminal.progressAnimation { 
    progressBar()
    progressBar()
}
progress.start()
```

**Comment by yoelp2k** [comment]
With one progress bar everything works perfectly 

With two I get the reported error 
Here is sample project to demonstrate the problem: https://github.com/yoelp2k/example-mordant-two-progress-bars
Running on windows 10, java17, IntelliJ IDEA 2022.1.3 (Ultimate Edition)

**Comment by ajalt** [comment]
So the issue is that the IntelliJ terminal doesn't support cursor movement commands, so it's not possible to animate anything that spans more than one line. We special case that terminal for single line animations by using a carriage return. 

Try running in a real terminal and it should work.

**Comment by yoelp2k** [comment]
OK, tried it on several windows terminals (git-bash, power-shell, cmd)
Fail! all tested windows terminals had no output at all (for the two lines example)
Surprisingly - the intellij terminal did work displaying two lines as expected - but fancy characters replaced with '?'
Running intellij's "run configuration" prints many lines (because of what you said about the one line problem) 

Note: I noticed that Gradle somehow manage to display multiple lines correctly. On every terminal I tested, linux, windows - whatever. So there must be some kind of a solution to this nasty annoying bug. Not sure how worth-while it is though

**Comment by ajalt** [comment]
So again it depends on how you are running the program. I'm guessing you're running through gradle, which redirects stdin and stdout. Since there's no way for mordant to tell whether you're running interactively in gradle vs being redirected to a file, it takes the safe approach and disables animations.

You can force the animations to play by forcing interactive output: `Terminal(ansiLevel=AnsiLevel.TRUECOLOR, interactive=true)`.

For the `?` characters, make sure your terminals are set to use UTF-8 code pages, and your JVM file encoding is set to UTF-8 as well ([here's how I set the file encoding in the samples](https://github.com/ajalt/mordant/blob/d7026d527869ba523d37e340bc2e4738a904e6d7/samples/markdown/build.gradle.kts#L8)).
